version: '3.9'

networks:
  laravel:

services:
  nginx: 
    image: nginx:latest
    container_name: nginx-server
    ports:
      - "8088:80"
    volumes:
       - ./src:/var/www/html
       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  

  mysql: 
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4036:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: rahasia
      MYSQL_ROOT_PASSWORD: rahasia
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - laravel

  php:
    image: php:8-fpm
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  phpmyadmin: 
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment: 
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rahasia
    networks:
      - laravel
    


